project1/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    path('places/', include('places.urls')),
    path('', include('about.urls')),
    path('', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project1/news/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list.as_view(), ),
    path('<int:id>/', views.post_detail, )
]

project1/places/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('dost/', views.places_list, ),
    path('pam/', views.pam_places_list, ),
    path('<int:id>/', views.place_detail, )
]

project1/project1/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

project1/comments/models.py
from django.db import models
from django.conf import settings

from news.models import New
from places.models import Place


class Comment(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    text = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(New, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.firstname} comment {self.text[0:20]} {self.date_created}'
    
    class Meta:
        unique_together = ['user', 'text', 'post']



class Review(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    text = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    place = models.ForeignKey(Place, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.firstname} comment {self.text[0:20]} {self.date_created}'

    class Meta:
        unique_together = ['user', 'text', 'place']



project1/galery/models.py
from django.db import models

project1/news/models.py
from django.db import models

class New(models.Model):
    image = models.ImageField(upload_to='news/')
    title = models.CharField(max_length=200)
    text_1 = models.TextField()
    quote = models.CharField(max_length=200)
    text_2 = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return f'/news/{self.id}/'

project1/places/models.py
from django.db import models

class Place(models.Model):
    name = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    is_pamyatnik = models.BooleanField(default=False)
    image_1 = models.ImageField(upload_to='place/')
    image_2 = models.ImageField(upload_to='place/')
    image_3 = models.ImageField(upload_to='place/')
    text_1 = models.TextField()
    text_2 = models.TextField()
    text_3 = models.TextField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        if self.is_pamyatnik:
            return f'/places/{self.id}/'
        if not self.is_pamyatnik:
            return f'/places/{self.id}/'

project1/users/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import (BaseUserManager, AbstractBaseUser,
                                        PermissionsMixin)


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)



class User(AbstractBaseUser, PermissionsMixin):
    avatar = models.ImageField(upload_to='users/')
    firstname = models.CharField(max_length=200)
    surname = models.CharField(max_length=200)
    email = models.EmailField(verbose_name='email address',
                              unique=True)
    is_staff = models.BooleanField(
        verbose_name='staff status',
        default=False,
    )
    is_active = models.BooleanField(
        verbose_name='active',
        default=True,
    )
    objects = UserManager()
    USERNAME_FIELD = 'email'

    def __str__(self):
        return self.email

project1/galery/views.py
from django.shortcuts import render

# Create your views here.

project1/news/views.py
from django.shortcuts import render
from django import forms
from django.db import IntegrityError
from .models import New
from django.views.generic import ListView
from comments.models import Comment


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = "__all__"


class post_list(ListView):
    paginate_by = 9
    model = New
    template_name = '../templates/News.html'


def post_detail(request, id):
    template_name = '../templates/newsmore.html'
    post = New.objects.get(id=id)
    comments_qt = len(Comment.objects.filter(post=post))
    comments = Comment.objects.filter(post=post)
    popular_news = New.objects.all()[:5]

    if request.method == 'POST':
        user = request.user
        text = request.POST['text']
        try:
            Comment.objects.create(user=user, text=text, post=post)
         
        except IntegrityError:
            return render(request, template_name, context)       


    context = {
        'post': post,
        'comments_qt': comments_qt,
        'comments': comments,
        'popular_news': popular_news,
    }

    return render(request, template_name, context)

project1/places/views.py
from django.shortcuts import redirect, render
from .models import Place
from comments.models import Review
from django.core.paginator import Paginator
from django.db import IntegrityError


def places_list(request):
    template_name = '../templates/place.html'
    places_list = Place.objects.filter(is_pamyatnik=False)
    places_list_count = Place.objects.filter(is_pamyatnik=False).count()
    dost_qt = Place.objects.filter(is_pamyatnik=False).count()
    pam_qt = Place.objects.filter(is_pamyatnik=True).count()

    context = {
        'places': places_list,
        'dost_qt': dost_qt,
        'pam_qt': pam_qt,
        'count': places_list_count,
    }
    if request.GET:
        title = request.GET['title']
        context['places'] = Place.objects.filter(is_pamyatnik=False).filter(title__icontains=title)
        context['count'] = Place.objects.filter(is_pamyatnik=False).filter(title__icontains=title).count()

    return render(request, template_name, context)


def place_detail(request, id):
    template_name = '../templates/Showplace.html'
    place = Place.objects.get(pk=id)
    reviews = Review.objects.filter(place=place)
    reviews_qt = Review.objects.filter(place=place).count()

    context = {
        'place': place,
        'reviews': reviews,
        'review_qt': reviews_qt,
    }

    if request.method == 'POST':
        user = request.user
        text = request.POST['text']
        try:
            Review.objects.create(user=user, text=text, place=place)
           
        except IntegrityError:
            return render(request, template_name, context)       

    return render(request, template_name, context)


def pam_places_list(request):
    template_name = '../templates/place.html'
    places_list = Place.objects.filter(is_pamyatnik=True)
    places_list_count = Place.objects.filter(is_pamyatnik=True).count()
    dost_qt = Place.objects.filter(is_pamyatnik=False).count()
    pam_qt = Place.objects.filter(is_pamyatnik=True).count()


    context = {
        'places': places_list,
        'dost_qt': dost_qt,
        'pam_qt': pam_qt,
        'count': places_list_count,
    }

    if request.GET:
        title = request.GET['title']
        context['places'] = Place.objects.filter(is_pamyatnik=True).filter(title__icontains=title)
        context['count'] = Place.objects.filter(is_pamyatnik=True).filter(title__icontains=title).count()

    return render(request, template_name, context)

project1/templates/Showplace.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'css/chief-slider.css' %}">
  <link rel="stylesheet" href="{% static 'css/Style.css' %}">
  <script defer src="{% static 'js/chief-slider.dev.js' %}"></script>

  <script src="https://kit.fontawesome.com/8210b99a89.js" crossorigin="anonymous"></script>
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      new ChiefSlider('.slider2', {
        loop: true,
        autoplay: false,
        swape: true
      });
    });
  </script>
</head>

<body>

  {% include 'header.html' %}

  <div class="showplace ">
    <div class="container size">
      <div class="name">
        <h1>{{ place.name }}</h1>
      </div>
      <div class="imginfo">
        <div class="imgleft">
          <img class="imgl" src="{{place.image_1.url}}" alt="">
        </div>
        <div class="imgright">
          <img class="imgrf" src="{{place.image_2.url}}" alt="">
          <img class="imgrs" src="{{place.image_3.url}}" alt="">
        </div>
      </div>
    </div>
  </div>

  <div class="slider2">
    <div class="slider__wrapper">
      <div class="slider__items">

        <div class="slider__item slider__itemshow">
          <div class="container size pp-50">
            <i class="fas fa-history mb-15 bxbr"></i>
            <p>{{place.text_1}}
              <br>
            </p>
          </div>
        </div>

        <div class="slider__item slider__itemshow">
          <div class="container size pp-50">
            <i class="fas fa-book mb-15"></i>
            <p>{{place.text_2}}</p>
          </div>
        </div>
        <div class="slider__item slider__itemshow">
          <div class="container size pp-50">
            <i class="fas fa-file-alt mb-15"></i>
            <p>{{place.text_3}}</p>
          </div>
        </div>
      </div>
    </div>
    <a href="#" class="slider__control" data-slide="prev"></a>
    <a href="#" class="slider__control" data-slide="next"></a>
    <ol class="slider__indicators">
      <li data-slide-to="0"></li>
      <li data-slide-to="1"></li>
      <li data-slide-to="2"></li>
    </ol>
  </div>


  <div class="commentnews testimonial ">
    <div class="container size">
      <h2> {{ review_qt }} Отзывов</h2>
      {% for review in reviews %}
      <div class="commnewsitems">
        <img src="{{ review.user.avatar.url }}" alt="">
        <div class="commentnewstext">
          <h6>{{review.user.firstname}}</h6>
          <span>{{ review.date_created }}</span>
          <p>{{ review.text }}</p>

        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  <div class="reccal">
    <div class="container size">
      {% if request.user %}
      <div class="commentpost">
        <h3> Отправить ваш отзыв</h3>
        <form id="contactForm" method="post">
          {% csrf_token %}
          <div class="bot">
            <textarea placeholder="Отзыв" name="text" cols="40" rows="10" required="" id="id_text"></textarea>
          </div>
          <button class="btnb">Опубликовать ваш отзыв</button>
        </form>
      </div>
      {% else %}
      <h3>Оставлять отызы могут только авторизированные пользователи</h3>
      {% endif %}
    </div>
  </div>


  {% include 'footer.html' %}
</body>

</html>

project1/templates/accountchange.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>change</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
				<form id="contactForm" method='post' enctype="multipart/form-data" class="login100-form validate-form flex-sb flex-w">
					
					{% csrf_token %}
					<span class="login100-form-title p-b-32">
						Изменить информацию 
					</span>			
					<div class="create">
						<span><a href="/">Главная</a></span>
					</div>	
					 
					<div class="addimg">
						<img class="avatar" src="{{ request.user.avatar.url }}" alt="">
						<input class="input100 inpsize" type="file" name="avatar" maxlength="150" required="true" id="id_avatar" accept="image/*">
					</div>
					
					
					<span class="txt1 p-b-11">
						Фамилия
					</span>
					<div class="wrap-input100 validate-input m-b-20" data-validate = "Surname is required">
						<input class="input100 inpsize" type="text" name="surname" maxlength="150" required="" id="id_surname" placeholder="{{request.user.surname}}">
						<span class="focus-input100"></span>
					</div>
					
					<span class="txt1 p-b-11">
						Имя
					</span>
					<div class="wrap-input100 validate-input m-b-20" data-validate = "Firstname is required">
						<input class="input100 inpsize" type="text" name="firstname" maxlength="150" required="" id="id_firstname"  placeholder="{{request.user.firstname}}">
						<span class="focus-input100"></span>
					</div>
					
					<span class="txt1 p-b-11">
						Электронная почта
					</span>
					
					<div class="wrap-input100 validate-input m-b-20" data-validate = "Email is required">
						<input class="input100 inpsize" type="text" name="email" maxlength="150" required="" id="id_email"  placeholder="{{request.user.email}}">
						<span class="focus-input100"></span>
					</div>
					
					<span class="txt1 p-b-11">
						Новый пароль
					</span>
					<div class="wrap-input100 validate-input m-b-20" data-validate = "Password is required">
						<span class="btn-show-pass">
							<i class="fa fa-eye"></i>
						</span>
						<input class="input100 inpsize" type="text" name="password" maxlength="150" required="" id="id_password">
						<span class="focus-input100"></span>
					</div>
					
						<span class="txt1 p-b-11">
						Новый пароль еще раз
					</span>
					<div class="wrap-input100 validate-input m-b-30" data-validate = "Password is required">
						<span class="btn-show-pass">
							<i class="fa fa-eye"></i>
						</span>
						<input class="input100 inpsize" type="text" name="password" maxlength="150" required="" id="id_password">
						<span class="focus-input100"></span>
					</div>
					
					
            <div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Изменить
						</button>
					</div>

				
				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{% static  'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

project1/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% include 'styles.html' %}
</head>
<body>
	
    {% include 'header.html' %}
    {% block content %}
    {% endblock %}
    {% include 'footer.html' %}
	{% include 'scripts.html' %}

</body>
</html>

project1/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}" />
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
	<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<!--===============================================================================================-->
</head>

<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
				<form class="login100-form validate-form flex-sb flex-w" method='post'>
					<span class="login100-form-title p-b-32">
						Вход в систему
					</span>
					<form id="contactForm" method='post' class="login100-form validate-form flex-sb flex-w">
						{% csrf_token %}
						<span class="txt1 p-b-11">
							электронная почта
						</span>
						<div class="wrap-input100 validate-input m-b-36" data-validate="Username is required">
							<input class="input100 inpsize" type="text" name="email" maxlength="150" required=""
								id="id_email" placeholder="{{request.user.email}}">
							<span class="focus-input100"></span>
						</div>

						<span class="txt1 p-b-11">
							Пароль
						</span>
						<div class="wrap-input100 validate-input m-b-12" data-validate="Password is required">
							<span class="btn-show-pass">
								<i class="fa fa-eye"></i>
							</span>
							<input class="input100 inpsize" type="text" name="password" maxlength="150" required=""
								id="id_password">
							<span class="focus-input100"></span>
						</div>

						<div class="create">
							<span>Нет аккаунта ? <a href="/register/"> Создать</a></span>
						</div>

						<div class="create">
							<span><a href="/">Главная</a></span>
						</div>


						<div class="container-login100-form-btn">
							<button class="login100-form-btn">
								Войти
							</button>
						</div>

					</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

	<!--===============================================================================================-->
	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
	<!--===============================================================================================-->
	<script src="vendor/animsition/js/animsition.min.js"></script>
	<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
	<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
	<!--===============================================================================================-->
	<script src="vendor/daterangepicker/moment.min.js"></script>
	<script src="vendor/daterangepicker/daterangepicker.js"></script>
	<!--===============================================================================================-->
	<script src="vendor/countdowntime/countdowntime.js"></script>
	<!--===============================================================================================-->
	<script src="js/main.js"></script>

</body>

</html>

project1/templates/newlogin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>register</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
				<form id="contactForm" method='post' enctype="multipart/form-data" class="login100-form validate-form flex-sb flex-w">
					{% csrf_token %}
					<span class="login100-form-title p-b-32">
						Регистрация
					</span>			

					<div class="addimg">					<span class="login100-form-title p-b-32">
						аватар
					</span>			
						<input class="input100 inpsize" type="file" name="avatar" maxlength="150" required="true" id="id_avatar" accept="image/*">
					</div>	
					
					<span class="txt1 p-b-11">
						Фамилия
					</span>
					<div class="wrap-input100 validate-input m-b-20" data-validate = "Surname is required">
						<input class="input100 inpsize" type="text" name="surname" maxlength="150" required="" id="id_surname">
						<span class="focus-input100"></span>
					</div>
					
					<span class="txt1 p-b-11">
						Имя
					</span>
					<div class="wrap-input100 validate-input m-b-20" data-validate = "Firstname is required">
						<input class="input100 inpsize" type="text" name="firstname" maxlength="150" required="" id="id_firstname" >
						<span class="focus-input100"></span>
					</div>
					
					<span class="txt1 p-b-11">
						Электронная почта
					</span>
					
					<div class="wrap-input100 validate-input m-b-20" data-validate = "Email is required">
						<input class="input100 inpsize" type="text" name="email" maxlength="150" required="" id="id_email">
						<span class="focus-input100"></span>
					</div>
					
					<span class="txt1 p-b-11">
						пароль
					</span>
					<div class="wrap-input100 validate-input m-b-20" data-validate = "Password is required">
						<span class="btn-show-pass">
							<i class="fa fa-eye"></i>
						</span>
						<input class="input100 inpsize" type="text" name="password" maxlength="150" required="" id="id_password">
						<span class="focus-input100"></span>
					</div>
					
						<span class="txt1 p-b-11">
						пароль еще раз
					</span>
					<div class="wrap-input100 validate-input m-b-30" data-validate = "Password is required">
						<span class="btn-show-pass">
							<i class="fa fa-eye"></i>
						</span>
						<input class="input100 inpsize" type="text" name="password" maxlength="150" required="" id="id_password">
						<span class="focus-input100"></span>
					</div>
					
					
            <div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Создать
						</button>
					</div>
					<div class="create">
						<span><a href="/">Главная</a></span>
					</div>
				
				</form>
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/daterangepicker/moment.min.js"></script>
	<script src="vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="js/main.js"></script>

</body>
</html>